packages:
  - "packages/core"
  - "packages/cli"
  - "packages/extension-browser"
  - "plugins/*"
  - "profiles/*"
  - "docs"
  - "examples/*"
allowBuilds:
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - esbuild
  - sharp
