/**
 * compile-schemas.ts — Build-time AJV schema compilation for CSP-safe runtime.
 *
 * Chrome MV3 extensions enforce a strict CSP that forbids `unsafe-eval`.
 * `Ajv.compile(schema)` at runtime uses `new Function(generatedCode)` which
 * is `eval`, so every translation response was failing validation silently
 * before this fix (CSP threw `EvalError: Evaluating a string as JavaScript
 * violates the following Content Security Policy directive`).
 *
 * The fix is the canonical AJV CSP escape hatch: precompile the four
 * translation output schemas at build time via `ajv/dist/standalone` into
 * a regular ES module. Runtime imports the validator *functions* and never
 * touches `new Function`.
 *
 * The output module is committed to `src/lib/schemas/compiled-validators.js`
 * (in `.gitignore` — regenerated on every build). Strict tsc in WXT picks
 * it up via the matching `.d.ts` we emit alongside.
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PKG_ROOT = resolve(__dirname, "..");
const SCHEMAS_DIR = resolve(PKG_ROOT, "src", "lib", "schemas");
const OUTPUT_FILE = resolve(SCHEMAS_DIR, "compiled-validators.js");
const OUTPUT_TYPES = resolve(SCHEMAS_DIR, "compiled-validators.d.ts");

const TOOLS = [
  "translate_incoming",
  "check_tone",
  "rewrite_outgoing",
  "brief_meeting",
] as const;

type JsonSchema = Record<string, unknown>;

/**
 * Mirrors the runtime `buildOutputSchema` in validation.ts. The raw schema
 * wraps an `input` and `output` block; we lift `output` to root + carry
 * `$defs` so internal `$ref`s still resolve.
 */
function buildOutputSchema(raw: JsonSchema, tool: string): JsonSchema {
  const properties = (raw.properties ?? {}) as Record<string, unknown>;
  const output = (properties.output ?? {}) as JsonSchema;
  const defs = (raw.$defs ?? {}) as JsonSchema;
  return {
    $id: `https://neurodock.org/schemas/${tool}.output.json`,
    $schema: "https://json-schema.org/draft/2020-12/schema",
    ...output,
    $defs: defs,
  };
}

function loadSchema(tool: string): JsonSchema {
  const path = join(SCHEMAS_DIR, `${tool}.schema.json`);
  if (!existsSync(path)) {
    throw new Error(
      `compile-schemas: ${path} missing. Run pnpm sync:schemas first.`,
    );
  }
  return JSON.parse(readFileSync(path, "utf8")) as JsonSchema;
}

export function compileSchemas(): { written: string } {
  mkdirSync(SCHEMAS_DIR, { recursive: true });
  const ajv = new Ajv2020({
    allErrors: true,
    strict: false,
    code: { source: true, esm: true },
  });
  const refs: Record<string, string> = {};
  for (const tool of TOOLS) {
    const raw = loadSchema(tool);
    const wrapped = buildOutputSchema(raw, tool);
    ajv.addSchema(wrapped, tool);
    refs[`validate_${tool}`] = tool;
  }
  const moduleSource = standaloneCode(ajv, refs);
  writeFileSync(OUTPUT_FILE, moduleSource, "utf8");

  const types = [
    "// Auto-generated by scripts/compile-schemas.ts.",
    "// Do not edit; regenerated on every build.",
    "",
    "export type ValidateFn = ((data: unknown) => boolean) & {",
    "  errors?: ReadonlyArray<{",
    "    instancePath: string;",
    "    schemaPath: string;",
    "    keyword: string;",
    "    message?: string;",
    "    params: Record<string, unknown>;",
    "  }> | null;",
    "};",
    "",
    ...TOOLS.map((t) => `export const validate_${t}: ValidateFn;`),
    "",
  ].join("\n");
  writeFileSync(OUTPUT_TYPES, types, "utf8");

  return { written: OUTPUT_FILE };
}

// Always run when invoked directly. `tsx scripts/compile-schemas.ts` from the
// package root is the only invocation surface; we don't import this module
// elsewhere. The previous `import.meta.url === file://...` guard failed on
// Windows because path normalisation differs between Node and tsx.
try {
  const result = compileSchemas();
  console.log(`[compile-schemas] wrote ${result.written}`);
} catch (cause) {
  console.error("[compile-schemas] FAILED");
  console.error(cause);
  process.exit(1);
}
